async function fetchPRDiff(owner, repo, pullNumber) {
  const token = process.env.GITHUB_TOKEN;

  const prRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${pullNumber}`,
    { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }
  );

  if (!prRes.ok) {
    const body = await prRes.text();
    console.error(`GitHub API error ${prRes.status}: ${body}`);
    process.exit(1);
  }

  const pr = await prRes.json();

  const filesRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${pullNumber}/files?per_page=100`,
    { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }
  );

  if (!filesRes.ok) {
    const body = await filesRes.text();
    console.error(`GitHub API error ${filesRes.status}: ${body}`);
    process.exit(1);
  }

  const files = await filesRes.json();

  const diff = files
    .map(f => `--- ${f.filename}\n${f.patch || '(binary or no diff)'}`)
    .join('\n\n');

  return {
    title: pr.title,
    branch: pr.head.ref,
    diff,
    files,
    number: pr.number,
    url: pr.html_url,
  };
}

async function postPRComment(owner, repo, pullNumber, body) {
  const token = process.env.GITHUB_TOKEN;

  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/issues/${pullNumber}/comments`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ body }),
    }
  );

  if (!res.ok) {
    const text = await res.text();
    console.error(`Failed to post comment ${res.status}: ${text}`);
    process.exit(1);
  }

  const data = await res.json();
  return { id: data.id, url: data.html_url };
}

async function approvePR(owner, repo, pullNumber, message) {
  const token = process.env.GITHUB_TOKEN;

  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${pullNumber}/reviews`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ event: 'APPROVE', body: message }),
    }
  );

  if (!res.ok) {
    const text = await res.text();
    console.error(`Failed to approve PR ${res.status}: ${text}`);
    process.exit(1);
  }

  const data = await res.json();
  return data.html_url;
}

const PRISM_SIGNATURE = '*Generated by [PRism]';

async function cleanupPRismComments(owner, repo, pullNumber, keep = 2) {
  const token = process.env.GITHUB_TOKEN;

  let page = 1, prismComments = [];
  while (true) {
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues/${pullNumber}/comments?per_page=100&page=${page}`,
      { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }
    );
    if (!res.ok) {
      console.error(`Failed to fetch comments page ${page}: HTTP ${res.status}`);
      break;
    }
    const batch = await res.json();
    if (!batch.length) break;
    prismComments.push(...batch.filter(c => c.body && c.body.includes(PRISM_SIGNATURE)));
    if (batch.length < 100) break;
    page++;
  }

  // sort newest-first explicitly — direction=desc is not supported by issues comments API
  prismComments.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

  for (const comment of prismComments.slice(keep)) {
    try {
      const res = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/issues/comments/${comment.id}`,
        { method: 'DELETE', headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }
      );
      if (!res.ok) console.error(`Failed to delete comment ${comment.id}: HTTP ${res.status}`);
      else console.log(`Deleted old PRism comment ${comment.id}`);
    } catch (err) {
      console.error(`Failed to delete comment ${comment.id}: ${err.message}`);
    }
  }
}

module.exports = { fetchPRDiff, postPRComment, approvePR, cleanupPRismComments, PRISM_SIGNATURE };
